---

- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::dockerhost'
    - 'role::dockerhost:repo'
    - 'role::dockerhost:install'
    - 'role::dockerhost:config'

- import_tasks: repo.yml
  tags:
    - 'role::dockerhost'
    - 'role::dockerhost:repo'

- import_tasks: installation.yml
  tags:
    - 'role::dockerhost'
    - 'role::dockerhost:install'

- import_tasks: configuration.yml
  tags:
    - 'role::dockerhost'
    - 'role::dockerhost:config'
